image: debovema/docker-mvn

before_script:
    - export PREPARE_RELEASE_SH_CHMOD=`stat --format '%a' ./prepareRelease.sh`
    - chmod u+x prepareRelease.sh
    - . ./prepareRelease.sh

release:
    script:
        - mvn -gs /home/m2/settings.xml -Dunleash.developmentVersion=$DEV_VERSION -Dunleash.releaseVersion=$RELEASE_VERSION -Dunleash.scmUsername=debovema -Dunleash.scmPasswordEnvVar=GIT_PASSWORD -Dunleash.profiles=release-profile,t3-archive -P release-profile,t3-archive unleash:perform
    only:
        - release
